version: 2
registries:
  maven-central:
    type: maven-repository
    url: https://repo.maven.apache.org/maven2/
  fabricmc:
    type: maven-repository
    url: https://maven.fabricmc.net/
  quiltmc:
    type: maven-repository
    url: https://maven.quiltmc.org/repository/release/
  parchment:
    type: maven-repository
    url: https://maven.parchmentmc.org/
  neoforge:
    type: maven-repository
    url: https://maven.neoforged.net/
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - maven-central
      - fabricmc
      - quiltmc
      - parchment
      - neoforge
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*modsdotgroovy*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "com.mojang:minecraft"
        update-types: ["version-update:semver-major"]
      - dependency-name: "*neoforge*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.quiltmc*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
