name: Snapshot
concurrency: ci-${{ github.ref }}
on:
    workflow_dispatch:
    push:
        branches:
            - 1.*
jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-java@v3
              with:
                  distribution: "temurin"
                  java-version: 17
            - name: Submit Dependencies
              uses: mikepenz/gradle-dependency-submission@v0.8.6
              with:
                  sub-module-mode: COMBINED
                  include-build-environment: true
            - uses: gradle/gradle-build-action@v2
              with:
                  arguments: checkLicenses build
                  cache-read-only: ${{ !startsWith(github.ref, 'refs/heads/1.') }}
            - uses: gradle/gradle-build-action@v2
              with:
                  arguments: publish
                  cache-read-only: ${{ !startsWith(github.ref, 'refs/heads/1.') }}
              env:
                  MAVEN_USER: github
                  MAVEN_PASSWORD: ${{ secrets.SNAPSHOT_MAVEN_PASSWORD }}
                  SNAPSHOT_MAVEN_URL: https://maven.lukebemish.dev/snapshots/

