name: Test
concurrency: ci-${{ github.ref }}
on: [workflow_dispatch, pull_request]
jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Setup Java
              run: |
                echo "JAVA_HOME=$JAVA_HOME_17_X64" >> "$GITHUB_ENV"
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: actions/cache/restore@v3
              with:
                path: |
                  .gradle/quilt-loom-cache
                  .gradle/loom-cache
                key: ${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}
                restore-keys: ${{ runner.os }}-gradle-
            - uses: gradle/gradle-build-action@v2
              name: Setup Gradle
              with:
                cache-read-only: ${{ !startsWith(github.ref, 'refs/heads/1.') }}
            - name: Build
              run: |
                ./gradlew checkLicenses build publish
              env:
                PR_NUMBER: ${{ github.event.pull_request.number }}
            - name: Archive publishable artifacts
              uses: actions/upload-artifact@v3
              with:
                name: artifacts
                path: build/repo
